### ISSUE TITLE
Launchable Tasks crashing on ESM version

### ISSUE THREAD

**Issue by vitor-ikon** [Hybridless/hybridless#12]
Log from running Classroom rebuild sessions index tool function:

[ '/usr/local/bin/node', '/usr/src/hybridless-runtime/proxy.mjs' ]

[Hybridless Runtime] - Error while decoding process arguments! SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at file:///usr/src/hybridless-runtime/proxy.mjs:37:24
    at file:///usr/src/hybridless-runtime/proxy.mjs:50:3
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)
ReferenceError: __dirname is not defined
    at file:///usr/src/hybridless-runtime/proxy.mjs:40:26
    at file:///usr/src/hybridless-runtime/proxy.mjs:50:3
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)

https://ca-central-1.console.aws.amazon.com/cloudwatch/home?region=ca-central-1#logsV2:log-groups/log-group/%2Faws%2Fecs%2FClassroomModuleAPIToolsessessions%2Fdev%2FTask0/log-events/ClassroomModuleAPIToolsessessionsTask0TDefdev%2FClassroomModuleAPIToolsessessionsTask0ContainerNamedev%2Fddf78d4a867646d3a0dc38422546f593

**Comment by gwdp** [comment]
Thank you for the report @vitor-ikon 
Release `0.1.1` with a simple fix for it; Please, let me know how it goes or if you need any hand on updating it;
Dont believe that the major will be generating any impact or issues on your side (usage).

**Comment by vitor-ikon** [comment]
Updated to `0.1.1` and ran the task, it exited with the following error (only difference I see it's the slightly different dirname reference error):

[ '/usr/local/bin/node', '/usr/src/hybridless-runtime/proxy.mjs' ]

[Hybridless Runtime] - Error while decoding process arguments! SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at file:///usr/src/hybridless-runtime/proxy.mjs:37:24
    at file:///usr/src/hybridless-runtime/proxy.mjs:51:3
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)
ReferenceError: dirname is not defined
    at file:///usr/src/hybridless-runtime/proxy.mjs:40:23
    at file:///usr/src/hybridless-runtime/proxy.mjs:51:3
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)

https://ca-central-1.console.aws.amazon.com/cloudwatch/home?region=ca-central-1#logsV2:log-groups/log-group/%2Faws%2Fecs%2FClassroomModuleAPIToolsessessions%2Fdev%2FTask0/log-events/ClassroomModuleAPIToolsessessionsTask0TDefdev%2FClassroomModuleAPIToolsessessionsTask0ContainerNamedev%2F3068cfc368e1447baeb5e43149b3b936

**Comment by gwdp** [comment]
Hey @vitor-ikon , `0.1.3` was just released with fixes to ESM launchable task builtin runtime; Lmk how it goes :)

**Comment by gwdp** [comment]
Closing as not answer within the last 3 week, assuming it was fixed; If any additional problems, please, create another ticket :)
